export const TEST_DATA = 'TEST_DATA';
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const FETCHED_POSTS_SUCCESS = 'FETCHED_POSTS_SUCCESS';
export const FETCHED_POSTS_FAILURE = 'FETCHED_POSTS_FAILURE';
